### PR TITLE
support allennlp==1.3.0

### PR DESCRIPTION
**Pull request by KoichiYasuoka**
It seems overlooked on PR #1, and https://github.com/allenai/allennlp/pull/4842 reminds us now. Sorry @tamuhey san for bad PR #2.

### CODE REVIEW

**Comment by tamuhey** [comment]
LGTM. Really appreciate your help, @KoichiYasuoka !

**Comment by KoichiYasuoka** [comment]
Thank you, @tamuhey san, for merging this PR, and do you have a plan to update [unofficial-udify](https://pypi.org/project/unofficial-udify/)?

**Comment by tamuhey** [comment]
@KoichiYasuoka san, I've just published new version: https://pypi.org/project/unofficial-udify/

**Comment by KoichiYasuoka** [comment]
Thank you @tamuhey san. Now I can use `en_udify-0.7.tar.gz` with `unofficial-udify==0.3.0` `allennlp==1.3.0` `camphr==0.7.2` `tokenizers==0.9.4` `sentencepiece==0.1.94` and `transformers==3.5.1`. And I'm trying to use `transformers 4.x` for https://github.com/PKSHATechnology-Research/camphr/pull/136 .

**Pull request merged**
